import type { LocalMediaSource, NewsSource } from '../types';

export const NEWS_SOURCES: NewsSource[] = [
  // ── Western Liberal ──────────────────────────────────────────────────────
  {
    id: 'bbc',
    name: 'BBC World',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Europe',
    country: 'UK',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://feeds.bbci.co.uk/news/world/rss.xml&id=bbc',
    description: 'UK public broadcaster. Center-left, Western framing. Credible but reflects British foreign policy alignment.',
  },
  {
    id: 'france24',
    name: 'France 24',
    bias: 'western-liberal',
    biasColor: 'left',
    lean: -1,
    region: 'Europe',
    country: 'France',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.france24.com/en/rss&id=france24',
    description: 'French international broadcaster. Pro-EU, Western liberal. Strong Africa and MENA coverage.',
  },
  {
    id: 'dw',
    name: 'Deutsche Welle',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Europe',
    country: 'Germany',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://rss.dw.com/atom/rss-en-all&id=dw',
    description: 'German public international broadcaster. Reliable, center-left, strong human rights focus.',
  },
  {
    id: 'apnews',
    name: 'AP / Guardian',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Global',
    country: 'USA',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.theguardian.com/world/rss&id=apnews',
    description: 'The Guardian World feed — center-left, internationally respected, clean RSS. Solid factual baseline.',
  },
  {
    id: 'reuters',
    name: 'Reuters',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Global',
    country: 'UK',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://news.yahoo.com/rss/world&id=reuters',
    description: 'Reuters/Yahoo world news RSS. Wire service aggregation. Most neutral major feed.',
  },

  // ── US Right ─────────────────────────────────────────────────────────────
  {
    id: 'foxnews',
    name: 'Fox News',
    bias: 'right',
    biasColor: 'right',
    lean: 3,
    region: 'Americas',
    country: 'USA',
    tier: 'tier2',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://moxie.foxnews.com/google-publisher/world.xml&id=foxnews',
    description: 'US right-wing cable news. Strong nationalist/conservative framing. High US domestic bias.',
  },
  {
    id: 'nypost',
    name: 'New York Post',
    bias: 'center-right',
    biasColor: 'right',
    lean: 2,
    region: 'Americas',
    country: 'USA',
    tier: 'tier2',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://nypost.com/feed/&id=nypost',
    description: 'US tabloid-style center-right. Murdoch-owned. More sensational than ideological.',
  },

  // ── Arab / Gulf ───────────────────────────────────────────────────────────
  {
    id: 'aljazeera',
    name: 'Al Jazeera',
    bias: 'arab-funded',
    biasColor: 'gulf',
    lean: -2,
    region: 'MENA',
    country: 'Qatar',
    tier: 'tier1',
    sourceType: 'state',
    rss: '/api/rss-proxy?url=https://www.aljazeera.com/xml/rss/all.xml&id=aljazeera',
    description: 'Qatar state-funded. Anti-Western, pro-Palestinian, pro-Muslim Brotherhood. Major voice in Arab world.',
  },
  {
    id: 'arabnews',
    name: 'Al-Monitor',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'MENA',
    country: 'USA',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://www.al-monitor.com/rss&id=arabnews',
    description: 'Al-Monitor — Independent Middle East news. Expert analysis, used by diplomats. No state funding, evidence-based.',
  },
  {
    id: 'mee',
    name: 'Middle East Eye',
    bias: 'pro-palestinian',
    biasColor: 'left',
    lean: -2,
    region: 'MENA',
    country: 'UK',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://www.middleeasteye.net/rss&id=mee',
    description: 'UK-based. Strong pro-Palestinian, often sympathetic to Muslim Brotherhood. Qatar-linked funding reported.',
  },

  // ── Israeli ───────────────────────────────────────────────────────────────
  {
    id: 'haaretz',
    name: 'Jerusalem Post',
    bias: 'israeli-center',
    biasColor: 'center',
    lean: 1,
    region: 'MENA',
    country: 'Israel',
    tier: 'tier2',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.jpost.com/rss/rssfeedsfrontpage.aspx&id=haaretz',
    description: 'Jerusalem Post. Leading Israeli English-language daily. Center-right Israeli perspective.',
  },
  {
    id: 'timesofisrael',
    name: 'Times of Israel',
    bias: 'israeli-center',
    biasColor: 'center',
    lean: 1,
    region: 'MENA',
    country: 'Israel',
    tier: 'tier2',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.timesofisrael.com/feed/&id=timesofisrael',
    description: 'Israeli center. English-language. More balanced than most Israeli outlets. Pro-Israel framing.',
  },

  // ── Russian / Kremlin ─────────────────────────────────────────────────────
  {
    id: 'rt',
    name: 'RT',
    bias: 'pro-kremlin',
    biasColor: 'state',
    lean: -3,
    region: 'Europe',
    country: 'Russia',
    tier: 'tier2',
    sourceType: 'state',
    rss: '/api/rss-proxy?url=https://www.rt.com/rss/&id=rt',
    description: 'Russian state media. Kremlin mouthpiece. Banned in EU. Important to include to understand Russian framing.',
  },
  {
    id: 'tass',
    name: 'TASS',
    bias: 'pro-kremlin',
    biasColor: 'state',
    lean: -3,
    region: 'Europe',
    country: 'Russia',
    tier: 'tier2',
    sourceType: 'state',
    rss: '/api/rss-proxy?url=https://tass.com/rss/v2.xml&id=tass',
    description: 'Official Russian state newswire. Pure Kremlin position. No editorial independence.',
  },

  // ── Chinese ───────────────────────────────────────────────────────────────
  {
    id: 'cgtn',
    name: 'Global Times',
    bias: 'pro-beijing',
    biasColor: 'state',
    lean: -3,
    region: 'Asia',
    country: 'China',
    tier: 'tier2',
    sourceType: 'state',
    rss: '/api/rss-proxy?url=https://www.globaltimes.cn/rss/outbrain.xml&id=cgtn',
    description: 'Global Times — CCP-controlled English tabloid. Hawkish nationalist perspective. China\'s most aggressive state media voice.',
  },
  {
    id: 'scmp',
    name: 'SCMP',
    bias: 'pro-beijing',
    biasColor: 'state',
    lean: -1,
    region: 'Asia',
    country: 'Hong Kong',
    tier: 'tier2',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.scmp.com/rss/91/feed&id=scmp',
    description: 'South China Morning Post. Hong Kong-based, Alibaba-owned. More nuanced than CGTN but Beijing-influenced.',
  },

  // ── Iranian ───────────────────────────────────────────────────────────────
  {
    id: 'presstv',
    name: 'Press TV',
    bias: 'iranian-state',
    biasColor: 'state',
    lean: -3,
    region: 'MENA',
    country: 'Iran',
    tier: 'tier2',
    sourceType: 'state',
    rss: '/api/rss-proxy?url=https://www.presstv.ir/rss.xml&id=presstv',
    description: 'Iranian state media in English. Anti-US, anti-Israel, pro-resistance axis framing.',
  },

  // ── OSINT / Investigative ─────────────────────────────────────────────────
  {
    id: 'bellingcat',
    name: 'Bellingcat',
    bias: 'osint',
    biasColor: 'osint',
    lean: -1,
    region: 'Global',
    country: 'Netherlands',
    tier: 'tier1',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://www.bellingcat.com/feed&id=bellingcat',
    description: 'Open-source investigative journalism. Fact-based, evidence-driven. Western-leaning but methodologically rigorous.',
  },
  {
    id: 'theintercept',
    name: 'The Intercept',
    bias: 'left',
    biasColor: 'left',
    lean: -2,
    region: 'Americas',
    country: 'USA',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://theintercept.com/feed/?rss&id=intercept',
    description: 'US left-wing investigative. Anti-surveillance, anti-empire. Strong on US foreign policy critique.',
  },

  // ── Indian ────────────────────────────────────────────────────────────────
  {
    id: 'thehindu',
    name: 'The Hindu',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Asia',
    country: 'India',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.thehindu.com/feeder/default.rss&id=thehindu',
    description: 'Indian center-left. Respected journalism, non-Western perspective on global events.',
  },

  // ── Global Broadcast / International ─────────────────────────────────────
  {
    id: 'npr',
    name: 'NPR World',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Americas',
    country: 'USA',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://feeds.npr.org/1004/rss.xml&id=npr',
    description: 'US public radio world news. Center-left, detail-rich. Strong domestic + international reporting.',
  },
  {
    id: 'cna',
    name: 'CNA (Singapore)',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Asia',
    country: 'Singapore',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.channelnewsasia.com/rssfeeds/8395986&id=cna',
    description: 'Channel News Asia. Singapore. Strong Asia-Pacific and MENA coverage. Generally balanced.',
  },
  {
    id: 'euronews',
    name: 'Euronews',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Europe',
    country: 'France',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.euronews.com/rss&id=euronews',
    description: 'Pan-European broadcaster. Multilingual, center-editorial, EU-friendly framing.',
  },
  {
    id: 'alarabiya',
    name: 'Al Arabiya (English)',
    bias: 'gulf-aligned',
    biasColor: 'gulf',
    lean: 1,
    region: 'MENA',
    country: 'UAE',
    tier: 'tier2',
    sourceType: 'state',
    rss: '/api/rss-proxy?url=https://english.alarabiya.net/tools/rss.xml&id=alarabiya',
    description: 'Saudi-backed. Pro-Gulf, anti-Iran. Rival to Al Jazeera. Key for Gulf perspective comparison.',
  },

  // ── Dynamic Social Topic Feeds (driven by selected UI filter) ───────────
  {
    id: 'x-topic',
    name: 'X Public (Topic Feed)',
    bias: 'right',
    biasColor: 'right',
    lean: 1,
    region: 'Global',
    country: 'Global',
    tier: 'tier3',
    sourceType: 'social',
    rss: '/api/rss-proxy?url=https://nitter.net/search/rss?f=tweets&q=__TOPIC__&id=x-topic',
    description: 'X (Twitter) public posts via topic search feed. Query updates with selected topic/filter.',
  },
  {
    id: 'meta-topic',
    name: 'Meta Public Mentions (Topic Feed)',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Global',
    country: 'Global',
    tier: 'tier3',
    sourceType: 'social',
    rss: '/api/rss-proxy?url=https://news.google.com/rss/search?q=site:facebook.com+__TOPIC__&hl=en-US&gl=US&ceid=US:en&id=meta-topic',
    description: 'Public Meta/Facebook post mentions from open web indexing, dynamically filtered by selected topic.',
  },

  // ── High-profile leadership feeds ───────────────────────────────────────
  {
    id: 'potus-x',
    name: 'POTUS (X)',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Americas',
    country: 'USA',
    tier: 'tier2',
    sourceType: 'social',
    rss: '/api/rss-proxy?url=https://nitter.net/POTUS/rss&id=potus-x',
    description: 'Official U.S. President social feed for direct statements.',
  },
  {
    id: 'ukpm-x',
    name: 'UK PM / 10 Downing (X)',
    bias: 'center-right',
    biasColor: 'center',
    lean: 1,
    region: 'Europe',
    country: 'UK',
    tier: 'tier2',
    sourceType: 'social',
    rss: '/api/rss-proxy?url=https://nitter.net/10DowningStreet/rss&id=ukpm-x',
    description: 'Official UK Prime Minister office social feed for direct announcements.',
  },
  {
    id: 'modi-x',
    name: 'PM Modi (X)',
    bias: 'center-right',
    biasColor: 'center',
    lean: 1,
    region: 'Asia',
    country: 'India',
    tier: 'tier2',
    sourceType: 'social',
    rss: '/api/rss-proxy?url=https://nitter.net/narendramodi/rss&id=modi-x',
    description: 'India PM social feed for direct statements and policy communication.',
  },

  // ── Social / Rumor Watch ────────────────────────────────────────────────
  {
    id: 'reddit-worldnews',
    name: 'Reddit r/worldnews',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Global',
    country: 'Global',
    tier: 'tier3',
    sourceType: 'social',
    rss: '/api/rss-proxy?url=https://www.reddit.com/r/worldnews/new/.rss&id=reddit-worldnews',
    description: 'Global public social feed. Fast signal, mixed reliability; corroborate before treating as fact.',
  },
  {
    id: 'reddit-lebanon',
    name: 'Reddit r/lebanon (Rumor Watch)',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'MENA',
    country: 'Lebanon',
    tier: 'tier3',
    sourceType: 'rumor',
    rss: '/api/rss-proxy?url=https://www.reddit.com/r/lebanon/new/.rss&id=reddit-lebanon',
    description: 'Community posts and eyewitness chatter. Unverified unless corroborated by multiple credible outlets.',
  },

  // ── Localized (Lebanon) ──────────────────────────────────────────────────
  {
    id: 'mtv-lebanon',
    name: 'MTV Lebanon',
    bias: 'center-right',
    biasColor: 'right',
    lean: 1,
    region: 'MENA',
    country: 'Lebanon',
    tier: 'tier2',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.mtv.com.lb/RSS&id=mtv-lebanon',
    description: 'Lebanese local TV newsroom feed for city and country-level updates.',
  },
  {
    id: 'the961',
    name: 'The 961 (Lebanon)',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'MENA',
    country: 'Lebanon',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://www.the961.com/feed/&id=the961',
    description: 'English-language Lebanese news portal. Local politics, society, and breaking events from Beirut.',
  },

  // ── European Country News ──────────────────────────────────────────────────
  {
    id: 'rfi',
    name: 'RFI (France)',
    bias: 'western-liberal',
    biasColor: 'left',
    lean: -1,
    region: 'Europe',
    country: 'France',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.rfi.fr/en/rss&id=rfi',
    description: 'Radio France Internationale — French public broadcaster in English. Strong Africa and Francophone coverage.',
  },
  {
    id: 'spiegel',
    name: 'Spiegel International (Germany)',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Europe',
    country: 'Germany',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.spiegel.de/international/index.rss&id=spiegel',
    description: "Germany's leading investigative weekly, English edition. Center-left, EU-friendly, strong investigative record.",
  },
  {
    id: 'skynews',
    name: 'Sky News (UK)',
    bias: 'center-right',
    biasColor: 'right',
    lean: 1,
    region: 'Europe',
    country: 'UK',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://feeds.skynews.com/feeds/rss/world.xml&id=skynews',
    description: 'UK commercial broadcaster. Center-right tabloid-adjacent tone. Fast breaking news.',
  },
  {
    id: 'ansa',
    name: 'ANSA (Italy)',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Europe',
    country: 'Italy',
    tier: 'tier2',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.ansa.it/english/news/rss.xml&id=ansa',
    description: "Italy's national wire service. English edition. Solid European and Mediterranean coverage.",
  },
  {
    id: 'kyivindependent',
    name: 'Kyiv Independent (Ukraine)',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Europe',
    country: 'Ukraine',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://kyivindependent.com/feed&id=kyivindependent',
    description: 'Ukrainian English-language independent. Essential for Ukraine war coverage from inside UK. Pro-Ukraine framing.',
  },
  {
    id: 'notesfrompoland',
    name: 'Notes from Poland',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Europe',
    country: 'Poland',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://notesfrompoland.com/feed/&id=notesfrompoland',
    description: 'English-language Polish current affairs. Rule of law, EU-Poland tensions, Eastern Europe politics.',
  },
  {
    id: 'politicoeu',
    name: 'Politico Europe',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Europe',
    country: 'Belgium',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.politico.eu/feed/&id=politicoeu',
    description: 'EU-focused political journalism. Essential for Brussels policy, NATO, and EU foreign policy.',
  },
  {
    id: 'euobserver',
    name: 'EUobserver',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Europe',
    country: 'Belgium',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://euobserver.com/rss&id=euobserver',
    description: 'Independent Brussels-based EU affairs outlet. Non-profit. EU institutions, policy, and democracy watchdog.',
  },
  {
    id: 'mailguardian',
    name: 'Mail & Guardian (Africa)',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Africa',
    country: 'South Africa',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://mg.co.za/feed/&id=mailguardian',
    description: 'South African independent. Investigative, pan-African perspective. Strong human rights focus.',
  },
  {
    id: 'allafrica',
    name: 'AllAfrica',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Africa',
    country: 'Global',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf&id=allafrica',
    description: 'Pan-African news aggregator. Aggregates from 500+ African publications. Broad continent coverage.',
  },

  // ── Telegram OSINT Channels (via RSSHub public instance) ─────────────────
  // rsshub.app/telegram/channel/{CHANNELNAME} → already in rss-proxy allowlist
  {
    id: 'tg-intelcrab',
    name: 'IntelCrab (Telegram)',
    bias: 'osint',
    biasColor: 'osint',
    lean: 0,
    region: 'Global',
    country: 'Global',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://rsshub.app/telegram/channel/intelcrab&id=tg-intelcrab',
    description: 'IntelCrab Telegram: OSINT aggregation of open-source intelligence. Conflict, geopolitics, breaking events.',
  },
  {
    id: 'tg-nexta',
    name: 'NEXTA TV (Telegram)',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Europe',
    country: 'Belarus',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://rsshub.app/telegram/channel/nexta_tv&id=tg-nexta',
    description: 'NEXTA: Belarusian exile media. Leading source on Belarus and Ukraine war. Anti-Lukashenko, pro-West.',
  },
  {
    id: 'tg-geoconfirmed',
    name: 'GeoConfirmed (Telegram)',
    bias: 'osint',
    biasColor: 'osint',
    lean: 0,
    region: 'Global',
    country: 'Global',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://rsshub.app/telegram/channel/GeoConfirmed&id=tg-geoconfirmed',
    description: 'GeoConfirmed: Geolocation verification of conflict footage. Ukrainian/Russian war footage geolocated and verified.',
  },
  {
    id: 'tg-wartranslated',
    name: 'War Translated (Telegram)',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Europe',
    country: 'Ukraine',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://rsshub.app/telegram/channel/wartranslated&id=tg-wartranslated',
    description: 'War Translated: Real-time translation of Ukrainian and Russian war communications. Primary source content.',
  },
  {
    id: 'tg-militaryland',
    name: 'Military Land (Telegram)',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Europe',
    country: 'Ukraine',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://rsshub.app/telegram/channel/militaryland_net&id=tg-militaryland',
    description: 'Military Land: Ukraine war front-line mapping and analysis. OSINT-based territorial control tracking.',
  },
  {
    id: 'tg-rybar',
    name: 'Rybar (Telegram — Russian OSINT)',
    bias: 'pro-kremlin',
    biasColor: 'state',
    lean: -2,
    region: 'Europe',
    country: 'Russia',
    tier: 'tier2',
    sourceType: 'social',
    rss: '/api/rss-proxy?url=https://rsshub.app/telegram/channel/rybar&id=tg-rybar',
    description: 'Rybar: Pro-Russian military Telegram channel. Russian nationalist perspective on Ukraine war. Included for perspective analysis.',
  },

  // ── OSINT Twitter/X Accounts (via Nitter) ────────────────────────────────
  {
    id: 'x-osintdefender',
    name: 'OSINTdefender (X)',
    bias: 'osint',
    biasColor: 'osint',
    lean: 0,
    region: 'Global',
    country: 'USA',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://nitter.net/OSINTdefender/rss&id=x-osintdefender',
    description: 'OSINTdefender on X: US defense/security OSINT. Monitors global military movements, conflict, breaking events.',
  },
  {
    id: 'x-intelbriefing',
    name: 'Intel Briefing (X)',
    bias: 'osint',
    biasColor: 'osint',
    lean: 0,
    region: 'Global',
    country: 'Global',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://nitter.net/intelbriefing/rss&id=x-intelbriefing',
    description: 'Intel Briefing on X: OSINT aggregator covering global intelligence, geopolitics, and breaking events.',
  },
  {
    id: 'x-jacobkipp',
    name: 'Jake Broe / War OSINT (X)',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Europe',
    country: 'USA',
    tier: 'tier3',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://nitter.net/JakeBroe/rss&id=x-jacobkipp',
    description: 'Jake Broe on X: Ukraine war analysis and OSINT. Western perspective with sourced commentary.',
  },

  // ── Tech / AI ────────────────────────────────────────────────────────────
  {
    id: 'techcrunch',
    name: 'TechCrunch',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Americas',
    country: 'USA',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://techcrunch.com/feed/&id=techcrunch',
    description: 'Leading tech startup and venture capital news. Silicon Valley-centric. Strong on AI, funding rounds, and product launches.',
  },
  {
    id: 'arstechnica',
    name: 'Ars Technica',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Americas',
    country: 'USA',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://feeds.arstechnica.com/arstechnica/index&id=arstechnica',
    description: 'Deep-dive technology journalism. Strong on AI, science, security, and policy. More technical and rigorous than TechCrunch.',
  },
  {
    id: 'theverge',
    name: 'The Verge',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Americas',
    country: 'USA',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.theverge.com/rss/index.xml&id=theverge',
    description: 'Consumer tech, gadgets, AI, and Big Tech policy. Vox Media. Accessible and culturally aware technology journalism.',
  },
  {
    id: 'venturebeat',
    name: 'VentureBeat AI',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Americas',
    country: 'USA',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://venturebeat.com/feed/&id=venturebeat',
    description: 'Enterprise tech and AI news. Focused on applied AI, LLMs, autonomous agents, and enterprise adoption.',
  },
  {
    id: 'wired',
    name: 'Wired',
    bias: 'center-left',
    biasColor: 'left',
    lean: -1,
    region: 'Americas',
    country: 'USA',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.wired.com/feed/rss&id=wired',
    description: 'Long-form tech culture and AI journalism. Condé Nast. Covers societal impact of technology and Silicon Valley power.',
  },
  {
    id: 'mit-tech-review',
    name: 'MIT Technology Review',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Americas',
    country: 'USA',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.technologyreview.com/feed/&id=mit-tech-review',
    description: 'MIT Media Lab publication. Academic-grade AI and emerging tech coverage. Most rigorous and unbiased tech outlet.',
  },
  {
    id: 'hackernews',
    name: 'Hacker News',
    bias: 'center-right',
    biasColor: 'right',
    lean: 1,
    region: 'Global',
    country: 'USA',
    tier: 'tier2',
    sourceType: 'social',
    rss: '/api/rss-proxy?url=https://news.ycombinator.com/rss&id=hackernews',
    description: 'Y Combinator community feed. Startup, dev, and AI discourse from engineers and founders. Strong libertarian/startup bias.',
  },
  {
    id: 'the-batch',
    name: 'The Batch (DeepLearning.AI)',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Global',
    country: 'USA',
    tier: 'tier2',
    sourceType: 'independent',
    rss: '/api/rss-proxy?url=https://www.deeplearning.ai/the-batch/feed/&id=the-batch',
    description: 'Andrew Ng\'s weekly AI newsletter. Curated AI research highlights, model releases, and industry news. No bias — pure signal.',
  },

  // ── Finance / Markets ─────────────────────────────────────────────────────
  {
    id: 'yahoo-finance',
    name: 'Yahoo Finance',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Global',
    country: 'USA',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://finance.yahoo.com/rss/topstories&id=yahoo-finance',
    description: 'Top financial news aggregator. Markets, earnings, M&A, macro economics. High-volume, fast signal.',
  },
  {
    id: 'marketwatch',
    name: 'MarketWatch',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Americas',
    country: 'USA',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://feeds.marketwatch.com/marketwatch/topstories/&id=marketwatch',
    description: 'Dow Jones financial news. Real-time market coverage, equities, macro analysis, and investing trends.',
  },
  {
    id: 'coindesk',
    name: 'CoinDesk',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Global',
    country: 'USA',
    tier: 'tier2',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.coindesk.com/arc/outboundfeeds/rss/&id=coindesk',
    description: 'Leading crypto/Web3 news outlet. Bitcoin, Ethereum, DeFi, regulation, and institutional adoption.',
  },
  {
    id: 'ft-tech',
    name: 'Financial Times (Tech)',
    bias: 'center-right',
    biasColor: 'right',
    lean: 1,
    region: 'Global',
    country: 'UK',
    tier: 'tier1',
    sourceType: 'mainstream',
    rss: '/api/rss-proxy?url=https://www.ft.com/technology?format=rss&id=ft-tech',
    description: 'FT Technology section. Premium business/finance journalism on Big Tech, AI policy, and global capital markets.',
  },

  // ── Synthetic / Intelligence ─────────────────────────────────────────────
  {
    id: 'gdelt',
    name: 'GDELT Intelligence',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Global',
    country: 'Global',
    tier: 'tier1',
    sourceType: 'independent',
    rss: '', // synthetic — fetched via /api/gdelt, not rss-proxy
    description: 'Global Database of Events, Language, and Tone. 100+ country/language corpus. Free, no API key.',
  },

  // ── Meta-aggregators / Monitoring (intelligence sources) ─────────────────
  {
    id: 'ground-news',
    name: 'Ground News',
    bias: 'center',
    biasColor: 'center',
    lean: 0,
    region: 'Global',
    country: 'Canada',
    tier: 'tier1',
    sourceType: 'intelligence',
    rss: '/api/rss-proxy?url=https://ground.news/feeds/blindspot-digest&id=ground-news',
    description: 'News bias aggregator. Cross-references 50,000+ sources to surface blind spots and coverage gaps across left/right/center. Unique: shows which stories only one side covers.',
  },
  {
    id: 'mts',
    name: 'Monitor The Situation',
    bias: 'center',
    biasColor: 'osint',
    lean: 0,
    region: 'Global',
    country: 'Global',
    tier: 'tier1',
    sourceType: 'intelligence',
    rss: '', // no public RSS — tracked via direct link
    description: 'Real-time geopolitical conflict monitoring dashboard. Tracks S1–S5 severity events across Conflict, Political, Humanitarian, Economic, Disaster categories. Integrates Kalshi prediction markets.',
  },
];

// Source map for O(1) lookup
export const SOURCE_MAP = new Map(NEWS_SOURCES.map(s => [s.id, s]));

function normalizeLocalSource(input: LocalMediaSource): NewsSource {
  const sourceType = input.sourceType ?? 'independent';
  const tier = input.tier ?? 'tier2';
  const region = input.country ? input.country : 'Local';
  const url = input.url.trim();
  const rss = url.startsWith('/api/rss-proxy?url=')
    ? url
    : `/api/rss-proxy?url=${encodeURIComponent(url)}&id=${encodeURIComponent(input.id)}`;

  return {
    id: input.id,
    name: input.name,
    bias: sourceType === 'state' ? 'state-media' : sourceType === 'social' || sourceType === 'rumor' ? 'center-right' : 'center',
    biasColor: sourceType === 'state' ? 'state' : sourceType === 'social' || sourceType === 'rumor' ? 'right' : 'center',
    tier,
    sourceType,
    lean: sourceType === 'social' || sourceType === 'rumor' ? 1 : 0,
    region,
    country: input.country ?? 'Local',
    rss,
    description: `${input.city ? `${input.city}, ` : ''}${input.country ?? 'Local'} user-added media source (${getSourceTypeLabel(sourceType)}).`,
  };
}

export function getLocalMediaSources(): NewsSource[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem('pos-settings');
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    const items: LocalMediaSource[] = Array.isArray(parsed?.localMediaSources) ? parsed.localMediaSources : [];
    return items
      .filter(item => item?.id && item?.name && item?.url)
      .map(normalizeLocalSource);
  } catch {
    return [];
  }
}

export function getAllSources(): NewsSource[] {
  return [...NEWS_SOURCES, ...getLocalMediaSources()];
}

export function getSourceById(sourceId: string): NewsSource | undefined {
  return SOURCE_MAP.get(sourceId) ?? getLocalMediaSources().find(s => s.id === sourceId);
}

// Color hex values for bias rendering
export const BIAS_COLORS: Record<string, string> = {
  right:   '#ef4444',
  left:    '#3b82f6',
  state:   '#8b5cf6',
  gulf:    '#f59e0b',
  center:  '#6b7280',
  osint:   '#06b6d4',
};

// Get contrasting text color for a bias color
export function getBiasTextClass(color: string): string {
  const map: Record<string, string> = {
    right:  'text-red-400',
    left:   'text-blue-400',
    state:  'text-purple-400',
    gulf:   'text-amber-400',
    center: 'text-gray-400',
    osint:  'text-cyan-400',
  };
  return map[color] ?? 'text-gray-400';
}

export function getBiasBgClass(color: string): string {
  const map: Record<string, string> = {
    right:  'bg-red-500/10 border-red-500/30',
    left:   'bg-blue-500/10 border-blue-500/30',
    state:  'bg-purple-500/10 border-purple-500/30',
    gulf:   'bg-amber-500/10 border-amber-500/30',
    center: 'bg-gray-500/10 border-gray-500/30',
    osint:  'bg-cyan-500/10 border-cyan-500/30',
  };
  return map[color] ?? 'bg-gray-500/10 border-gray-500/30';
}

export function getSourceTypeLabel(sourceType?: NewsSource['sourceType']): string {
  switch (sourceType) {
    case 'social': return 'Social';
    case 'rumor': return 'Rumor';
    case 'independent': return 'Independent';
    case 'state': return 'State';
    case 'intelligence': return 'Intelligence';
    default: return 'Mainstream';
  }
}
